version: 2

sources:
  - name: knoema_economy_data_atlas
    database: knoema_economy_data_atlas
    schema: economy
    tables:
      - name: exratescc2018 #daily exchange rates
      - name: usindssp2020  #daily us trading history